exclude-newer = "7 days"
constraint-dependencies = [
    "mistralai!=2.4.6",
    "guardrails-ai!=0.10.1",
]

[exclude-newer-package]
breakout-turbo-env = "2026-08-12T13:25:25Z"
gradoom = "2026-08-12T13:25:25Z"
stable-retro-turbo = "2026-08-12T13:25:25Z"
supermariobrosnes-turbo = "2026-08-12T13:25:25Z"
vizdoom-turbo = "2026-08-12T13:25:25Z"
