exclude-newer = "7 days"
constraint-dependencies = [
    "mistralai!=2.4.6",
    "guardrails-ai!=0.10.1",
]
[exclude-newer-package]
env-breakoutatari2600-turbo-native = false
env-doom-turbo-torch = false
env-stableretro-turbo = false
env-supermariobrosnes-turbo-emu = false
env-vizdoom-turbo = false
